name: Clone Repository

on:
  push:
    branches:
    - main
  workflow_dispatch:


jobs:
  clone:
    runs-on: ubuntu-latest

    steps:

    - name: Token generator
      uses: actions/create-github-app-token@v1
      id: app-token
      with:
        app-id: ${{ vars.APP_ID }}
        private-key: ${{ secrets.PRIVATE_KEY }}

    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        repository: 'devwithkrishna/azure-terraform-modules'
        token: ${{ steps.app-token.outputs.token }}
        fetch-depth: 1

# - name: Verify Repository Access

#   run: |
#     curl -L \
#       -H "Accept: application/vnd.github+json" \
#       -H "Authorization: Bearer ${{ env.GH_APP_TOKEN }}" \
#       -H "X-GitHub-Api-Version: 2022-11-28" \
#       https://api.github.com/repos/devwithkrishna/azure-terraform-modules
