name: Clone Repository

on:
  push:
    branches:
    - main

jobs:
  clone:
    runs-on: ubuntu-latest

    steps:

    - name: Token generator
      uses: githubofkrishnadhas/github-access-using-githubapp@v1
      with:
        github_app_id: ${{ secrets.TOKEN_GENERATOR_APPID }}
        github_app_private_key: ${{ secrets.TOKEN_GENERATOR_PRIVATE_KEY }}
        github_account_type: 'user'

    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        repository: 'devwithkrishna/azure-terraform-modules'
        token: ${{ env.GH_APP_TOKEN }}
        fetch-depth: 1

    - name: Verify Repository Access
      run: |
        curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ env.GH_APP_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/devwithkrishna/azure-terraform-modules
